#!/usr/bin/env bash
# demo.sh — DQ Gate Policy: dual-MCP demo
#
# Spins up TWO isolated Flex Gateway stacks side by side:
#
#   Stack A  (port 8081) — "parks-guests"   — DQ score 95  → requests PASS
#   Stack B  (port 8082) — "parks-guests-b" — DQ score 65  → requests BLOCKED
#
# Both share the same mock images but have independent object stores, so
# each cache entry is completely separate.
#
# Usage:
#   ./playground/demo.sh            # run the full demo
#   ./playground/demo.sh --cleanup  # tear down and remove containers only
#
# Prerequisites: Docker + docker compose v2 (or docker-compose v1)
# The Flex Gateway WASM must already be built:  make build

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

COMPOSE_FILE="$SCRIPT_DIR/docker-compose-demo.yaml"

# ── colours ──────────────────────────────────────────────────────────────────
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

info()    { echo -e "${CYAN}▶ $*${NC}"; }
success() { echo -e "${GREEN}✔ $*${NC}"; }
warn()    { echo -e "${YELLOW}⚠ $*${NC}"; }
fail()    { echo -e "${RED}✘ $*${NC}"; }
header()  { echo -e "\n${BOLD}━━━ $* ━━━${NC}"; }

# ── docker compose compat ─────────────────────────────────────────────────────
if docker compose version &>/dev/null 2>&1; then
  DC="docker compose"
else
  DC="docker-compose"
fi

cleanup() {
  info "Tearing down demo stacks..."
  $DC -f "$COMPOSE_FILE" down --remove-orphans 2>/dev/null || true
}

if [[ "${1:-}" == "--cleanup" ]]; then
  cleanup
  success "Done."
  exit 0
fi

trap 'echo ""; warn "Interrupted — cleaning up..."; cleanup; exit 1' INT TERM

# ── generate docker-compose-demo.yaml ────────────────────────────────────────
header "Generating docker-compose-demo.yaml"

# Locate the built WASM (same logic as the Makefile)
WASM_PATH="$PROJECT_ROOT/target/wasm32-wasip1/release/dq_gate_policy.wasm"
if [[ ! -f "$WASM_PATH" ]]; then
  fail "WASM not found at $WASM_PATH"
  echo "  Run  make build  first."
  exit 1
fi

# Read the Flex image version from the existing docker-compose.yaml
FLEX_IMAGE=$(grep 'mulesoft/flex-gateway' "$SCRIPT_DIR/docker-compose.yaml" | head -1 \
  | sed 's/.*image: //' | tr -d '"' | tr -d "'")
info "Using Flex image: $FLEX_IMAGE"

# Write a standalone compose file for the demo (two full stacks)
cat > "$COMPOSE_FILE" <<YAML
# Auto-generated by demo.sh — do not edit by hand.
version: "3.3"

services:
  # ── Stack A: parks-guests (HIGH score = PASS) ──────────────────────────────
  flex-a:
    image: ${FLEX_IMAGE}
    ports:
      - "8081:8081"
    volumes:
      - ./config-demo-a:/usr/local/share/mulesoft/flex-gateway/conf.d/
    depends_on: [backend-a, cdgclogin-a, cdgcapi-a, osauth-a, os-a]

  backend-a:
    image: kennethreitz/httpbin

  cdgclogin-a:
    image: python:3.12-alpine
    environment: { ROLE: cdgclogin, PORT: "80" }
    volumes:
      - ./mocks/mock_server.py:/mock_server.py:ro
    command: python /mock_server.py

  cdgcapi-a:
    image: python:3.12-alpine
    environment: { ROLE: cdgcapi, PORT: "80", DQ_SCORE: "95" }
    volumes:
      - ./mocks/mock_server.py:/mock_server.py:ro
    command: python /mock_server.py

  osauth-a:
    image: python:3.12-alpine
    environment: { ROLE: objectstoreauth, PORT: "80" }
    volumes:
      - ./mocks/mock_server.py:/mock_server.py:ro
    command: python /mock_server.py

  os-a:
    image: python:3.12-alpine
    environment: { ROLE: objectstore, PORT: "80" }
    volumes:
      - ./mocks/mock_server.py:/mock_server.py:ro
    command: python /mock_server.py

  # ── Stack B: parks-guests-b (LOW score = BLOCK) ────────────────────────────
  flex-b:
    image: ${FLEX_IMAGE}
    ports:
      - "8082:8081"
    volumes:
      - ./config-demo-b:/usr/local/share/mulesoft/flex-gateway/conf.d/
    depends_on: [backend-b, cdgclogin-b, cdgcapi-b, osauth-b, os-b]

  backend-b:
    image: kennethreitz/httpbin

  cdgclogin-b:
    image: python:3.12-alpine
    environment: { ROLE: cdgclogin, PORT: "80" }
    volumes:
      - ./mocks/mock_server.py:/mock_server.py:ro
    command: python /mock_server.py

  cdgcapi-b:
    image: python:3.12-alpine
    environment: { ROLE: cdgcapi, PORT: "80", DQ_SCORE: "65" }
    volumes:
      - ./mocks/mock_server.py:/mock_server.py:ro
    command: python /mock_server.py

  osauth-b:
    image: python:3.12-alpine
    environment: { ROLE: objectstoreauth, PORT: "80" }
    volumes:
      - ./mocks/mock_server.py:/mock_server.py:ro
    command: python /mock_server.py

  os-b:
    image: python:3.12-alpine
    environment: { ROLE: objectstore, PORT: "80" }
    volumes:
      - ./mocks/mock_server.py:/mock_server.py:ro
    command: python /mock_server.py
YAML

success "docker-compose-demo.yaml written."

# ── generate per-stack Flex configs ──────────────────────────────────────────
header "Writing Flex Gateway configs"

# Read the registration.yaml (shared — local mode, not org-specific)
REG_FILE="$SCRIPT_DIR/config/registration.yaml"
if [[ ! -f "$REG_FILE" ]]; then
  fail "No registration.yaml found at $REG_FILE"
  echo "  See the README for how to generate one with Anypoint Platform."
  exit 1
fi

# Helper: write a full config dir for one stack
write_stack_config() {
  local dir="$1"  # e.g. config-demo-a
  local asset_id="$2"
  local cdgclogin_host="$3"   # docker service name
  local cdgcapi_host="$4"
  local osauth_host="$5"
  local os_host="$6"
  local backend_host="$7"

  mkdir -p "$SCRIPT_DIR/$dir/custom-policies"

  # Copy shared files
  cp "$REG_FILE" "$SCRIPT_DIR/$dir/registration.yaml"
  cp "$SCRIPT_DIR/config/logging.yaml" "$SCRIPT_DIR/$dir/logging.yaml"
  cp "$SCRIPT_DIR/config/custom-policies/dq_gate_policy_definition.yaml" \
     "$SCRIPT_DIR/$dir/custom-policies/dq_gate_policy_definition.yaml"
  cp "$SCRIPT_DIR/config/custom-policies/dq_gate_policy_implementation.yaml" \
     "$SCRIPT_DIR/$dir/custom-policies/dq_gate_policy_implementation.yaml"

  # Write the api.yaml for this stack
  cat > "$SCRIPT_DIR/$dir/api.yaml" <<YAML
apiVersion: gateway.mulesoft.com/v1alpha1
kind: ApiInstance
metadata:
  name: ingress-http
spec:
  address: http://0.0.0.0:8081
  services:
    upstream:
      address: http://${backend_host}
      routes:
        - config:
            destinationPath: /anything/mcp/
  policies:
    - policyRef:
        name: dq-gate-policy-flex-v1-0
        namespace: default
      config:
        cdgcLoginUrl: http://${cdgclogin_host}
        cdgcBaseApiUrl: http://${cdgcapi_host}
        cdgcOrgUsername: dummy-cdgc-username
        cdgcOrgPassword: dummy-cdgc-password
        cdgcAssetId: ${asset_id}
        warnThreshold: 90
        blockThreshold: 80
        scoreAggregation: min
        refreshIntervalSeconds: 30
        failOpenOnCdgcError: true
        blockOnUnknownScore: false
        objectStoreAuthUrl: http://${osauth_host}/token
        objectStoreUrl: http://${os_host}
        objectStoreClientId: dummy-client-id
        objectStoreClientSecret: dummy-client-secret
        objectStoreName: dq-gate-demo-store
YAML
}

write_stack_config "config-demo-a" \
  "parks-guests-asset" \
  "cdgclogin-a" "cdgcapi-a" "osauth-a" "os-a" "backend-a"

write_stack_config "config-demo-b" \
  "parks-guests-b-asset" \
  "cdgclogin-b" "cdgcapi-b" "osauth-b" "os-b" "backend-b"

success "Stack configs written."

# ── start stacks ─────────────────────────────────────────────────────────────
header "Starting demo stacks"
$DC -f "$COMPOSE_FILE" up -d
info "Waiting for Flex gateways to be ready..."

wait_for_port() {
  local port=$1 label=$2
  for i in $(seq 1 30); do
    if curl -s -o /dev/null "http://localhost:$port/anything/mcp/"; then
      success "$label is up (port $port)"
      return 0
    fi
    sleep 2
  done
  fail "$label did not become ready on port $port after 60s"
  return 1
}

wait_for_port 8081 "Stack A (parks-guests)"
wait_for_port 8082 "Stack B (parks-guests-b)"

# ── demo calls ────────────────────────────────────────────────────────────────
header "Demo: Stack A — parks-guests (DQ score 95, blockThreshold 80)"
info "Calling Stack A → expect HTTP 200 (PASS)"
echo ""

RESP_A=$(curl -s -w "\n%{http_code}" -X POST http://localhost:8081/anything/mcp/ \
  -H "Content-Type: application/json" \
  -d '{"jsonrpc":"2.0","method":"tools/list","id":1}')
BODY_A=$(echo "$RESP_A" | head -n -1)
CODE_A=$(echo "$RESP_A" | tail -n 1)

echo "  HTTP $CODE_A"
echo "  Body: $BODY_A" | head -c 300
echo ""

if [[ "$CODE_A" == "200" ]]; then
  success "Stack A PASSED as expected ✔"
else
  warn "Stack A returned $CODE_A (unexpected)"
fi

echo ""
header "Demo: Stack B — parks-guests-b (DQ score 65, blockThreshold 80)"
info "Calling Stack B → expect HTTP 400/403 (BLOCKED by DQ gate)"
echo ""

RESP_B=$(curl -s -w "\n%{http_code}" -X POST http://localhost:8082/anything/mcp/ \
  -H "Content-Type: application/json" \
  -d '{"jsonrpc":"2.0","method":"tools/list","id":1}')
BODY_B=$(echo "$RESP_B" | head -n -1)
CODE_B=$(echo "$RESP_B" | tail -n 1)

echo "  HTTP $CODE_B"
echo "  Body: $BODY_B" | head -c 300
echo ""

if [[ "$CODE_B" == "400" || "$CODE_B" == "403" || "$CODE_B" == "503" ]]; then
  success "Stack B BLOCKED as expected ✔"
else
  warn "Stack B returned $CODE_B (check logs — may need cache to populate first)"
fi

# ── live score mutation demo ──────────────────────────────────────────────────
echo ""
header "Bonus: mutate Stack B score live (65 → 95) and retry"
info "Pushing new score to cdgcapi-b mock..."

$DC -f "$COMPOSE_FILE" exec -T cdgcapi-b \
  sh -c 'wget -q -O- --method=PUT --body-data="{\"score\":95}" \
    --header="Content-Type: application/json" http://localhost/score' || \
  warn "Could not push score via exec — try manually: docker exec <cdgcapi-b> ..."

info "Waiting ${BOLD}31s${NC} for cache TTL (refreshIntervalSeconds=30) to expire..."
sleep 31

info "Retrying Stack B after score update..."
RESP_B2=$(curl -s -w "\n%{http_code}" -X POST http://localhost:8082/anything/mcp/ \
  -H "Content-Type: application/json" \
  -d '{"jsonrpc":"2.0","method":"tools/list","id":1}')
CODE_B2=$(echo "$RESP_B2" | tail -n 1)
BODY_B2=$(echo "$RESP_B2" | head -n -1)

echo "  HTTP $CODE_B2"
echo "  Body: $BODY_B2" | head -c 300
echo ""

if [[ "$CODE_B2" == "200" ]]; then
  success "Stack B now PASSES after score update ✔"
else
  warn "Stack B returned $CODE_B2 after score update"
fi

# ── summary ───────────────────────────────────────────────────────────────────
echo ""
header "Summary"
echo -e "  Stack A (parks-guests,   score=95):  HTTP ${GREEN}${CODE_A}${NC}"
echo -e "  Stack B (parks-guests-b, score=65):  HTTP ${RED}${CODE_B}${NC}  → blocked by DQ gate"
echo -e "  Stack B after score→95, TTL flush:   HTTP ${GREEN}${CODE_B2}${NC}"
echo ""
info "Stacks are still running. To tear down:"
echo "  ./playground/demo.sh --cleanup"
echo "  # or: docker compose -f playground/docker-compose-demo.yaml down"
echo ""
